// Copyright (c) Dapplo. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using Dapplo.Ini.Ui.Enums;

namespace Dapplo.Ini.Ui.Attributes;

/// <summary>
/// Configures the overall layout of the settings window generated by the UI framework.
/// </summary>
/// <remarks>
/// <para>
/// Apply this attribute to the <em>assembly</em> or to a dedicated marker class/interface
/// to control the window-level layout.  When applied to a specific section interface it
/// affects only that section's container.
/// </para>
/// <para>
/// When this attribute is absent the default layout is
/// <see cref="UiTabLayout.HorizontalTabs"/>.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // In AssemblyInfo.cs or any file in the consuming project:
/// [assembly: UiLayout(UiTabLayout.VerticalTabs, WindowTitle = "Application Settings")]
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
public sealed class UiLayoutAttribute : Attribute
{
    /// <summary>
    /// Gets the tab layout style for the settings window.
    /// </summary>
    public UiTabLayout TabLayout { get; }

    /// <summary>
    /// Initialises a new instance of <see cref="UiLayoutAttribute"/>.
    /// </summary>
    /// <param name="tabLayout">The tab layout style.</param>
    public UiLayoutAttribute(UiTabLayout tabLayout = UiTabLayout.HorizontalTabs)
    {
        TabLayout = tabLayout;
    }

    /// <summary>
    /// Gets or sets the title shown in the settings window title bar.
    /// Defaults to <c>"Settings"</c> when not specified.
    /// </summary>
    public string? WindowTitle { get; set; }

    /// <summary>
    /// Gets or sets the minimum width of the settings window, in device-independent pixels.
    /// </summary>
    public double MinWidth { get; set; } = 480;

    /// <summary>
    /// Gets or sets the minimum height of the settings window, in device-independent pixels.
    /// </summary>
    public double MinHeight { get; set; } = 320;

    /// <summary>
    /// Gets or sets whether the settings window supports dark/light mode theming.
    /// Defaults to <c>true</c>.
    /// </summary>
    public bool SupportsDarkMode { get; set; } = true;
}
