// Copyright (c) Dapplo. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

namespace Dapplo.Ini.Ui.Attributes;

/// <summary>
/// Marks an INI section interface as a page (tab) in the settings window and configures
/// its display properties.
/// </summary>
/// <remarks>
/// <para>
/// When an INI section interface carries this attribute it will appear as a separate page
/// or tab inside the settings window generated by the UI framework.  Multiple sections can
/// share the same <see cref="Category"/> to be grouped under a parent node in a tree-style
/// navigation (vertical-tabs layout) or shown as nested tabs.
/// </para>
/// <para>
/// When this attribute is omitted the section is still included in the settings window;
/// the page title defaults to the section name (interface name without leading <c>I</c>).
/// </para>
/// </remarks>
/// <example>
/// <code>
/// [UiPage(Title = "General", Order = 0)]
/// [IniSection("General")]
/// public interface IGeneralSettings : IIniSection { … }
///
/// [UiPage(Title = "Network", Category = "Advanced", Order = 10)]
/// [IniSection("Network")]
/// public interface INetworkSettings : IIniSection { … }
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
public sealed class UiPageAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the display title of the page/tab.
    /// When omitted the section name is used as the title.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Gets or sets an optional category that groups several pages under a common parent
    /// in a tree-style navigation (vertical-tabs layout).
    /// </summary>
    public string? Category { get; set; }

    /// <summary>
    /// Gets or sets the display order of this page within the settings window (or within
    /// its <see cref="Category"/>).  Lower values appear first.  Defaults to <c>0</c>.
    /// </summary>
    public int Order { get; set; }

    /// <summary>
    /// Gets or sets an optional icon resource key or path used by the UI framework to
    /// display a small icon next to the page title.
    /// </summary>
    public string? Icon { get; set; }
}
