// Copyright (c) Dapplo. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System.IO;
using System.Windows;
using Dapplo.Ini;
using Dapplo.Ini.Ui.DemoApp.Configuration;

namespace Dapplo.Ini.Ui.DemoApp;

/// <summary>
/// Application entry point.
/// </summary>
/// <remarks>
/// On startup this class:
/// <list type="number">
///   <item>
///     <description>
///       Builds an <see cref="IniConfig"/> backed by a per-user settings file in
///       <c>%APPDATA%\DappIniDemo\settings.ini</c>.
///     </description>
///   </item>
///   <item>
///     <description>
///       Registers the three section implementations (<see cref="IGeneralSettings"/>,
///       <see cref="INetworkSettings"/>, <see cref="IAppearanceSettings"/>).
///       The concrete implementations are auto-generated by
///       <c>Dapplo.Ini.Generator</c> as <c>*Impl</c> classes.
///     </description>
///   </item>
///   <item>
///     <description>
///       Creates and shows the <see cref="MainWindow"/> with the live section instances.
///     </description>
///   </item>
/// </list>
/// On exit the current settings are written back to the INI file.
/// </remarks>
public partial class App : Application
{
    private IniConfig?           _config;
    private IGeneralSettings?    _general;
    private INetworkSettings?    _network;
    private IAppearanceSettings? _appearance;

    protected override void OnStartup(StartupEventArgs e)
    {
        base.OnStartup(e);

        var settingsDir  = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
            "DappIniDemo");
        Directory.CreateDirectory(settingsDir);

        // Build the IniConfig and register all sections.
        // The *Impl types are generated by Dapplo.Ini.Generator.
        _general    = new GeneralSettingsImpl();
        _network    = new NetworkSettingsImpl();
        _appearance = new AppearanceSettingsImpl();

        _config = IniConfigRegistry
            .ForFile("settings.ini")
            .AddSearchPath(settingsDir)
            .SetWritablePath(settingsDir)
            .RegisterSection(_general)
            .RegisterSection(_network)
            .RegisterSection(_appearance)
            .Build();

        // Load existing settings from disk (if the file exists); missing file is fine.
        _config.Load();

        var mainWindow = new MainWindow(_general, _network, _appearance);
        MainWindow = mainWindow;
        mainWindow.Show();
    }

    protected override void OnExit(ExitEventArgs e)
    {
        // Persist settings to disk when the application closes.
        _config?.SaveAsync().GetAwaiter().GetResult();
        base.OnExit(e);
    }
}
