// Copyright (c) Dapplo. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System.Windows;
using Dapplo.Ini.Interfaces;
using Dapplo.Ini.Ui.DemoApp.Configuration;
using Dapplo.Ini.Ui.DemoApp.Windows;

namespace Dapplo.Ini.Ui.DemoApp;

/// <summary>
/// Main application window — displays current setting values and provides an
/// <em>Open Settings</em> button that launches the settings dialog.
/// </summary>
public partial class MainWindow : Window
{
    private readonly IGeneralSettings    _general;
    private readonly INetworkSettings    _network;
    private readonly IAppearanceSettings _appearance;

    /// <summary>
    /// Initialises the main window with the live section instances provided by
    /// <see cref="App"/>.
    /// </summary>
    public MainWindow(
        IGeneralSettings    general,
        INetworkSettings    network,
        IAppearanceSettings appearance)
    {
        _general    = general;
        _network    = network;
        _appearance = appearance;

        InitializeComponent();
        RefreshDisplay();
    }

    // ── Titlebar window-chrome button handlers ────────────────────────────────

    private void MinimizeButton_Click(object sender, RoutedEventArgs e)
        => WindowState = WindowState.Minimized;

    private void MaximizeRestoreButton_Click(object sender, RoutedEventArgs e)
    {
        WindowState = WindowState == WindowState.Maximized
            ? WindowState.Normal
            : WindowState.Maximized;

        // Update the glyph: □ when normal, ❐ when maximised.
        MaximizeRestoreButton.Content = WindowState == WindowState.Maximized ? "\u2750" : "\u25A1";
    }

    private void CloseButton_Click(object sender, RoutedEventArgs e)
        => Close();

    // ── Settings dialog ────────────────────────────────────────────────────────

    private void OpenSettingsButton_Click(object sender, RoutedEventArgs e)
    {
        /*
         * The SettingsWindow receives an ordered sequence of
         *   (compile-time UiPageMetadata, live IIniSection) pairs.
         *
         * The compile-time UiPageMetadata descriptors are generated by
         * Dapplo.Ini.Ui.Generator into static *UiDescriptor classes.
         * Using these avoids any runtime reflection to discover UI structure.
         *
         * Alternatively you could call UiMetadataReader.ReadPage<T>() here —
         * the result is identical but uses reflection.
         */
        var settingsWindow = new SettingsWindow(new[]
        {
            (GeneralSettingsUiDescriptor.Page,    (IIniSection)_general),
            (AppearanceSettingsUiDescriptor.Page, (IIniSection)_appearance),
            (NetworkSettingsUiDescriptor.Page,    (IIniSection)_network),
        })
        {
            Owner = this,
        };

        // ShowDialog() blocks until the user confirms or cancels.
        // Apply/Rollback is handled *inside* SettingsWindow via UiSettingsManager.
        settingsWindow.ShowDialog();

        // Refresh the main window to show any changes that were applied.
        RefreshDisplay();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// <summary>Updates all TextBlock labels to reflect the current section values.</summary>
    private void RefreshDisplay()
    {
        AppNameValue.Text  = _general.ApplicationName;
        StartupValue.Text  = _general.StartWithWindows ? "Yes" : "No";
        LanguageValue.Text = _general.Language.ToString();

        DarkModeValue.Text   = _appearance.DarkMode ? "On" : "Off";
        AccentColorValue.Text = _appearance.AccentColor.ToString();
        FontSizeValue.Text   = $"{_appearance.FontSize} pt";

        UseProxyValue.Text = _network.UseProxy ? "Yes" : "No";
        ProxyValue.Text    = _network.UseProxy
            ? $"{_network.ProxyHost}:{_network.ProxyPort}"
            : "(direct)";
    }
}
